services:
    # Servicio para la aplicación Laravel
    web:
        build:
            context: .
            dockerfile: ./Dockerfile
        image: apitimbrado/latest
        container_name: apitimbrado-app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - apitimbrado-network
        ports:
            - "5173:5173"

    db:
        image: mysql:8.0
        container_name: apitimbradodb
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
        volumes:
        - dbdata:/var/lib/mysql
        ports:
        - "3306:3306"
        networks:
        - apitimbrado-network

    # Nginx Service
    nginx:
        image: nginx:alpine
        container_name: apitimbrado_nginx
        restart: unless-stopped
        tty: true
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - .:/var/www
            - ./nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - apitimbrado-network


# Red para conectar los servicios
networks:
    apitimbrado-network:
        driver: bridge

volumes:
    dbdata:
