@echo off
cd C:\laragon\www\api-timbradocfdi

echo Creando migraciones faltantes de CFDI40...

php artisan make:migration create_catalogo_aduana_table
php artisan make:migration create_catalogo_codigo_postal_table
php artisan make:migration create_catalogo_estado_table
php artisan make:migration create_catalogo_exportacion_table
php artisan make:migration create_catalogo_impuesto_table
php artisan make:migration create_catalogo_meses_table
php artisan make:migration create_catalogo_metodo_pago_table
php artisan make:migration create_catalogo_moneda_table
php artisan make:migration create_catalogo_num_pedimento_aduana_table
php artisan make:migration create_catalogo_objeto_imp_table
php artisan make:migration create_catalogo_pais_table
php artisan make:migration create_catalogo_patente_aduanal_table
php artisan make:migration create_catalogo_periodicidad_table
php artisan make:migration create_catalogo_tasa_o_cuota_table
php artisan make:migration create_catalogo_tipo_factor_table
php artisan make:migration create_catalogo_c__colonia_table
php artisan make:migration create_catalogo_c__localidad_table
php artisan make:migration create_catalogo_c__municipio_table

echo ✅ Migraciones generadas correctamente.
pause
